# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_HPMICRO) += hpm6800evk.dtb
dtb-$(CONFIG_ARCH_HPMICRO) += hpm6e00evk.dtb
dtb-$(CONFIG_ARCH_HPMICRO) += hpm6p00evk.dtb
dtb-$(CONFIG_ARCH_HPMICRO) += hpm6360evk.dtb
dtb-$(CONFIG_ARCH_HPMICRO) += hpm6750evk2.dtb